# Generated by Django 3.2.8 on 2021-10-15 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=64)),
                ('author_username', models.CharField(max_length=64)),
                ('author_avatar', models.TextField()),
                ('created_at', models.CharField(max_length=64)),
                ('text', models.TextField()),
            ],
        ),
    ]
